### ISSUE TITLE
Status API Gives Invalid Timestamp

### ISSUE THREAD

**Issue by liam-middlebrook** [redxdev/hvzsite-old#70]
[The `/status` endpoint](https://hvz.rit.edu/api/v1/status) on the API will **always** return the game start time in `pre-game` mode. I don't think this was the intended behavior since the rest of this endpoint has the difference between the current and start times.

```
{  
    "status":"pre-game",
    "game":{  
        "start":1429491600,
        "end":1429912800,
        "time":{  
            "days":13,
            "hours":12,
            "minutes":29,
            "seconds":45,
            "timestamp":1429491600 # < this says 2100 not the above diff!
        }
    }
}
```

**Comment by redxdev** [comment]
The timestamp field is supposed to be the Unix timestamp that the diff represents, not the diff itself. "timestamp" should be the start time if we are in pre-game. It will be the end time during the game, which is also intended. It is a somewhat pointless field (you can easily figure out the value yourself) but it allows users of the API to not have to check what the game status is in order to figure out what timestamp to use.

**Comment by redxdev** [comment]
Issue is invalid; behavior is as intended.
